FROM python:3.12

WORKDIR /app

# Copiar TODO antes de instalar
COPY . .

# Instalar Poetry y dependencias
RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root