"""se adiciona fecha de inicio a la sesion

Revision ID: cb32988344c6
Revises: ab0dd81e7622
Create Date: 2025-03-26 07:11:04.447007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb32988344c6'
down_revision: Union[str, None] = 'ab0dd81e7622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('date_start', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_sessions_date_start'), 'sessions', ['date_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_date_start'), table_name='sessions')
    op.drop_column('sessions', 'date_start')
    # ### end Alembic commands ###
